manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointer-move-scroll
      import: app/west.yml
  self:
    path: config
